/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_database_free: (a: number, b: number) => void;
export const __wbg_databasebuilder_free: (a: number, b: number) => void;
export const __wbg_extractor_free: (a: number, b: number) => void;
export const __wbg_extractorbuilder_free: (a: number, b: number) => void;
export const database_lookup: (a: number, b: number, c: number) => [number, number, number];
export const database_lookupIp: (a: number, b: number, c: number) => [number, number, number];
export const database_lookupPattern: (a: number, b: number, c: number) => [number, number, number];
export const database_new: (a: number, b: number) => [number, number, number];
export const database_stats: (a: number) => [number, number, number];
export const databasebuilder_addEntry: (a: number, b: number, c: number, d: any) => [number, number];
export const databasebuilder_addIp: (a: number, b: number, c: number, d: any) => [number, number];
export const databasebuilder_addLiteral: (a: number, b: number, c: number, d: any) => [number, number];
export const databasebuilder_addPattern: (a: number, b: number, c: number, d: any) => [number, number];
export const databasebuilder_build: (a: number) => [number, number, number, number];
export const databasebuilder_new: (a: number) => number;
export const extractor_extract: (a: number, b: number, c: number) => [number, number, number];
export const extractorbuilder_build: (a: number) => [number, number, number];
export const extractorbuilder_extractBitcoin: (a: number, b: number) => number;
export const extractorbuilder_extractDomains: (a: number, b: number) => number;
export const extractorbuilder_extractEmails: (a: number, b: number) => number;
export const extractorbuilder_extractEthereum: (a: number, b: number) => number;
export const extractorbuilder_extractHashes: (a: number, b: number) => number;
export const extractorbuilder_extractIpv4: (a: number, b: number) => number;
export const extractorbuilder_extractIpv6: (a: number, b: number) => number;
export const extractorbuilder_extractMonero: (a: number, b: number) => number;
export const extractorbuilder_minDomainLabels: (a: number, b: number) => number;
export const extractorbuilder_new: () => number;
export const version: () => [number, number];
export const init: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
