[package]
name = "mdbook-project-version"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mdbook-project-version"
path = "src/main.rs"

[dependencies]
mdbook = { version = "0.4", default-features = false }
serde_json = "1.0"
toml = "0.8"
