[package]
name = "matchy-ac"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version = "1.74"
license.workspace = true
repository.workspace = true
description = "Offset-based, zero-copy Aho-Corasick automaton"
readme = "../../README.md"

[dependencies]
matchy-match-mode = { path = "../matchy-match-mode", version = "2.0.0" }
zerocopy = { version = "=0.8.31", features = ["derive"] }

[lints]
workspace = true
