[package]
name = "matchy-ac"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Offset-based Aho-Corasick automaton for matchy (internal)"
readme = "../../README.md"

[dependencies]
matchy-match-mode = { path = "../matchy-match-mode", version = "2.0.0" }
zerocopy.workspace = true
memchr.workspace = true

[lints]
workspace = true
