[book]
authors = ["Seth Hall"]
language = "en"
multilingual = false
src = "src"
title = "Matchy Documentation"
description = "Documentation for Matchy - Fast database for IP address and string matching"

[build]
build-dir = "html"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/sethhall/matchy"
edit-url-template = "https://github.com/sethhall/matchy/edit/main/book/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]
no-section-label = true
favicon = "theme/favicon.png"
# SVG favicon for modern browsers with theme support
favicon-svg = "theme/logo-light.svg"


[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
line-numbers = true

[preprocessor.project-version]
command = "cargo run --manifest-path mdbook-project-version/Cargo.toml --quiet"

# Enable command execution for examples
[preprocessor.cmdrun]
command = "./run-cmdrun.sh"


# Enable Mermaid diagrams
[preprocessor.mermaid]
command = "mdbook-mermaid"
